export const achievements = [
  {
    title: "Жисмоний тарбия ва спорт соҳасидаги маълумоти:",
    ratings: [
      {
        title: "олий",
        rating: 10,
      },
      {
        title: "қайта тайёрлаш",
        rating: 5,
      },
    ],
  },
];

// 4 ta filial. key — teacher.region.region da saqlanadigan qiymat bilan bir xil.
export const FILIALS = [
  { key: "Toshkent", name: "JTSBMQTMO Instituti" },
  { key: "Nukus", name: "JTSBMQTMOI Nukus Filiali" },
  { key: "Fargʻona", name: "JTSBMQTMOI Fargʻona Filiali" },
  { key: "Samarqand", name: "JTSBMQTMOI Samarqand Filiali" },
];

export const directions = [
  "I. Sport taʼlim muassasalari rahbar va oʻrinbosarlari",
  "II. Sport taʼlim muassasalari yoʻriqchi-uslubchilari",
  "III. Sport turlarini rivojlantirish respublika markazlari, Olimpiya va paralimpiya sport turlariga tayyorlash markazlari, ixtisoslashtirilgan sport maktablari, ixtisoslashtirilgan olimpiya zaxiralari maktablari trenerlari",
  "IV. Sport maktablari trenerlari",
  "V. Sport psixologlari",
  "VI. Oliy taʼlim muassasalarining jismoniy tarbiya va sport yoʻnalishlari boʻyicha rahbar va pedagog kadrlari",
  "VII. Kasbiy taʼlim tashkilotlari jismoniy tarbiya fani oʻqituvchilari (jismoniy tarbiya va sportga ixtisoslashtirilganlar bundan mustasno)",
  "VIII. Umumiy oʻrta va oʻrta maxsus taʼlim tashkilotlari jismoniy tarbiya fani oʻqituvchilari",
  "IX. Maktabgacha taʼlim tashkilotlari jismoniy tarbiya yoʻriqchilari",
];

export const FILIAL_KEYS = FILIALS.map((f) => f.key);

// Har bir viloyat qaysi filialga tegishli. region — filial kaliti.
export const provinces = [
  {
    title: "Toshkent shahri",
    region: "Toshkent",
  },
  {
    title: "Toshkent viloyati",
    region: "Toshkent",
  },
  {
    title: "Jizzax viloyati",
    region: "Toshkent",
  },
  {
    title: "Sirdaryo viloyati",
    region: "Toshkent",
  },
  {
    title: "Qoraqalpog'iston Respublikasi",
    region: "Nukus",
  },
  {
    title: "Xorazm viloyati",
    region: "Nukus",
  },
  {
    title: "Buxoro viloyati",
    region: "Nukus",
  },
  {
    title: "Samarqand viloyati",
    region: "Samarqand",
  },
  {
    title: "Qashqadaryo viloyati",
    region: "Samarqand",
  },
  {
    title: "Navoiy viloyati",
    region: "Samarqand",
  },
  {
    title: "Surxondaryo viloyati",
    region: "Samarqand",
  },
  {
    title: "Fargʻona viloyati",
    region: "Fargʻona",
  },
  {
    title: "Andijon viloyati",
    region: "Fargʻona",
  },
  {
    title: "Namangan viloyati",
    region: "Fargʻona",
  },
];

// region — province obyekti ({title, region}) yoki filial kaliti (string) bo'lishi mumkin.
export const getFilialKey = (region) => {
  if (!region) return null;
  return typeof region === "string" ? region : region.region || null;
};

export const getFilialByKey = (key) =>
  FILIALS.find((f) => f.key === key) || null;

// VM 2022-07-04/355-son qarori 3-ilova NIZOM 19-band — maxsus yutuqlar (18 ta).
// Ulardan biriga (tasdiqlangan) ega bo'lgan tinglovchi muqobil malaka oshirishga o'tadi.
export const SPECIAL_ITEMS = [
  "O'zbekiston Respublikasida xizmat ko'rsatgan sport ustozi faxriy unvoni",
  "O'zbekiston Respublikasida xizmat ko'rsatgan yoshlar murabbiysi faxriy unvoni",
  "O'zbekiston Respublikasi xalq Mutaxassissi faxriy unvoni",
  "O'zbekiston iftixori faxriy unvoni",
  "O'zbekiston Respublikasida xizmat ko'rsatgan sportchi faxriy unvoni",
  "So'nggi 4 yilda Olimpiya va Paralimpiya o'yinlarida g'olib va sovrindor bo'lgan sportchilar va ularni tayyorlagan trenerlar",
  "O'zbekiston Fanlar akademiyasi akademigi ilmiy unvoni",
  "So'nggi 4 yilda falsafa doktori (PhD) yoki fan doktori (DSc) darajasi uchun dissertatsiya himoya qilish",
  "So'nggi 4 yilda DSc dissertatsiyasiga ilmiy maslahatchi yoki 2 ta PhD dissertatsiyasiga ilmiy rahbarlik qilish",
  "So'nggi 2 yilda dotsent yoki professor ilmiy unvoni olganligi",
  "So'nggi 4 yilda xorijda malaka oshirish/stajirovka o'tashi (malaka oshirish ≥1 oy, stajirovka ≥3 oy)",
  "So'nggi 2 yilda yakka mualliflikda jismoniy tarbiya va sport bo'yicha darslik yoki o'quv qo'llanma nashr etish",
  "Xalqaro shaxmat federatsiyasi (FIDE) reytingida 1 800 va undan yuqori ball",
  "Qoraqalpog'iston Respublikasida xizmat ko'rsatgan sport ustozi faxriy unvoni",
  "Qoraqalpog'iston Respublikasida xizmat ko'rsatgan yoshlar murabbiysi faxriy unvoni",
  "Qoraqalpog'iston Respublikasi xalq ta'limi Mutaxassissi faxriy unvoni",
  "Qoraqalpog'iston Respublikasida xizmat ko'rsatgan sportchi faxriy unvoni",
  "Tuman(shahar)larning 'Eng yaxshi maktab sport klubi' reytingida 1–5-o'rinni egallagan maktab jismoniy tarbiya Mutaxassislari",
];

// O'zbekiston viloyatlari va tumanlar
export const DISTRICTS = {
  "Toshkent shahri": [
    "Bektemir tumani",
    "Chilonzor tumani",
    "Mirobod tumani",
    "Mirzo Ulug'bek tumani",
    "Olmazor tumani",
    "Sergeli tumani",
    "Shayxontohur tumani",
    "Uchtepa tumani",
    "Yakkasaroy tumani",
    "Yangihayot tumani",
    "Yashnobod tumani",
    "Yunusobod tumani",
  ],
  "Toshkent viloyati": [
    "Angren shahri",
    "Bekobod shahri",
    "Chirchiq shahri",
    "Nurafshon shahri",
    "Ohangaron shahri",
    "Olmaliq shahri",
    "Yangiyo'l shahri",
    "Bekobod tumani",
    "Bo'ka tumani",
    "Bo'stonliq tumani",
    "Chinoz tumani",
    "Ohangaron tumani",
    "Oqqo'rg'on tumani",
    "O'rtachirchiq tumani",
    "Parkent tumani",
    "Piskent tumani",
    "Qibray tumani",
    "Quyichirchiq tumani",
    "Toshkent tumani",
    "Yangiyo'l tumani",
    "Yuqorichirchiq tumani",
    "Zangiota tumani",
  ],
  "Jizzax viloyati": [
    "Jizzax shahri",
    "Arnasoy tumani",
    "Baxmal tumani",
    "Do'stlik tumani",
    "Forish tumani",
    "G'allaorol tumani",
    "Mirzacho'l tumani",
    "Paxtakor tumani",
    "Sharof Rashidov tumani",
    "Yangiobod tumani",
    "Zafarobod tumani",
    "Zarbdor tumani",
    "Zomin tumani",
  ],
  "Sirdaryo viloyati": [
    "Guliston shahri",
    "Shirin shahri",
    "Yangiyer shahri",
    "Boyovut tumani",
    "Guliston tumani",
    "Mirzaobod tumani",
    "Oqoltin tumani",
    "Sardoba tumani",
    "Sayxunobod tumani",
    "Sirdaryo tumani",
    "Xovos tumani",
  ],
  "Qoraqalpog'iston Respublikasi": [
    "Nukus shahri",
    "Amudaryo tumani",
    "Beruniy tumani",
    "Bo'zatov tumani",
    "Chimboy tumani",
    "Ellikqal'a tumani",
    "Kegeyli tumani",
    "Mo'ynoq tumani",
    "Nukus tumani",
    "Qonliko'l tumani",
    "Qo'ng'irot tumani",
    "Qorao'zak tumani",
    "Sho'manoy tumani",
    "Taxiatosh tumani",
    "Taxtako'pir tumani",
    "To'rtko'l tumani",
    "Xo'jayli tumani",
  ],
  "Xorazm viloyati": [
    "Urganch shahri",
    "Xiva shahri",
    "Bog'ot tumani",
    "Gurlan tumani",
    "Qo'shko'pir tumani",
    "Shovot tumani",
    "Tuproqqal'a tumani",
    "Urganch tumani",
    "Xazorasp tumani",
    "Xiva tumani",
    "Xonqa tumani",
    "Yangiariq tumani",
    "Yangibozor tumani",
  ],
  "Buxoro viloyati": [
    "Buxoro shahri",
    "Kogon shahri",
    "Buxoro tumani",
    "G'ijduvon tumani",
    "Jondor tumani",
    "Kogon tumani",
    "Olot tumani",
    "Peshku tumani",
    "Qorako'l tumani",
    "Qorovulbozor tumani",
    "Romitan tumani",
    "Shofirkon tumani",
    "Vobkent tumani",
  ],
  "Samarqand viloyati": [
    "Samarqand shahri",
    "Kattaqo'rg'on shahri",
    "Bulung'ur tumani",
    "Ishtixon tumani",
    "Jomboy tumani",
    "Kattaqo'rg'on tumani",
    "Narpay tumani",
    "Nurobod tumani",
    "Oqdaryo tumani",
    "Pastdarg'om tumani",
    "Paxtachi tumani",
    "Payariq tumani",
    "Qo'shrabot tumani",
    "Samarqand tumani",
    "Toyloq tumani",
    "Urgut tumani",
  ],
  "Qashqadaryo viloyati": [
    "Qarshi shahri",
    "Shahrisabz shahri",
    "Chiroqchi tumani",
    "Dehqonobod tumani",
    "G'uzor tumani",
    "Kasbi tumani",
    "Kitob tumani",
    "Ko'kdala tumani",
    "Koson tumani",
    "Mirishkor tumani",
    "Muborak tumani",
    "Nishon tumani",
    "Qamashi tumani",
    "Qarshi tumani",
    "Shahrisabz tumani",
    "Yakkabog' tumani",
  ],
  "Navoiy viloyati": [
    "Navoiy shahri",
    "Zarafshon shahri",
    "Karmana tumani",
    "Konimex tumani",
    "Navbahor tumani",
    "Nurota tumani",
    "Qiziltepa tumani",
    "Tomdi tumani",
    "Uchquduq tumani",
    "Xatirchi tumani",
  ],
  "Surxondaryo viloyati": [
    "Termiz shahri",
    "Angor tumani",
    "Bandixon tumani",
    "Boysun tumani",
    "Denov tumani",
    "Jarqo'rg'on tumani",
    "Muzrobod tumani",
    "Oltinsoy tumani",
    "Qiziriq tumani",
    "Qumqo'rg'on tumani",
    "Sariosiyo tumani",
    "Sherobod tumani",
    "Sho'rchi tumani",
    "Termiz tumani",
    "Uzun tumani",
  ],
  "Fargʻona viloyati": [
    "Farg'ona shahri",
    "Marg'ilon shahri",
    "Qo'qon shahri",
    "Quvasoy shahri",
    "Beshariq tumani",
    "Bog'dod tumani",
    "Buvayda tumani",
    "Dang'ara tumani",
    "Farg'ona tumani",
    "Furqat tumani",
    "Oltiariq tumani",
    "O'zbekiston tumani",
    "Qo'shtepa tumani",
    "Quva tumani",
    "Rishton tumani",
    "So'x tumani",
    "Toshloq tumani",
    "Uchko'prik tumani",
    "Yozyovon tumani",
  ],
  "Andijon viloyati": [
    "Andijon shahri",
    "Xonobod shahri",
    "Andijon tumani",
    "Asaka tumani",
    "Baliqchi tumani",
    "Bo'z tumani",
    "Buloqboshi tumani",
    "Izboskan tumani",
    "Jalaquduq tumani",
    "Marhamat tumani",
    "Oltinko'l tumani",
    "Paxtaobod tumani",
    "Qo'rg'ontepa tumani",
    "Shahrixon tumani",
    "Ulug'nor tumani",
    "Xo'jaobod tumani",
  ],
  "Namangan viloyati": [
    "Namangan shahri",
    "Chortoq tumani",
    "Chust tumani",
    "Kosonsoy tumani",
    "Mingbuloq tumani",
    "Namangan tumani",
    "Norin tumani",
    "Pop tumani",
    "To'raqo'rg'on tumani",
    "Uchqo'rg'on tumani",
    "Uychi tumani",
    "Yangiqo'rg'on tumani",
  ],
};
